### ISSUE TITLE
Doesn't Appear to be AOT ready yet

### ISSUE THREAD

**Issue by JonForest** [moff/angular2-flash-messages#11]
The latest version of angular-2-flash-messages works fine with a regular `ng s`, but when I try to precompile with the aot flag, I get the following:
```
➜  angcore git:(moderator-user-interactions) ✗ ng s --aot=true
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingUnexpected value 'FlashMessagesModule' imported by the module 'AppModule'
```

**Comment by moff** [comment]
Hi @JonForest 
I've just updated package, please check it out and let me know

**Comment by berndartmueller** [comment]
I still get this error after updating the package:

`can't resolve module ./flash-messages.component from /Users/Bernd/Projekte/web/node_modules/angular2-flash-messages/module/module.d.ts
Error: Cannot read property 'FlashMessagesComponent' of undefined, resolving symbol FlashMessagesModule in /Users/Bernd/Projekte/web/node_modules/angular2-flash-messages/module/module.d.ts, resolving symbol FlashMessagesModule in /Users/Bernd/Projekte/web/node_modules/angular2-flash-messages/module/module.d.ts
    at simplifyInContext (/Users/Bernd/Projekte/web/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/Bernd/Projekte/web/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/Bernd/Projekte/web/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/Bernd/Projekte/web/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
Compilation failed`

But maybe it is because I compiled the fork on my laptop and run "npm pack".

**Comment by moff** [comment]
Hi, @berndartmueller !

I've just updated the package - check it out and let me know. Thanks for a feedback!

**Comment by moff** [comment]
@JonForest do you still experience that issue with latest package version(1.0.8)?
