### ISSUE TITLE
Support for Angular 6.x

### ISSUE THREAD

**Issue by jonathan-bird** [moff/angular2-flash-messages#42]
Request for support of Angular 6.x

**Comment by Kens1520** [comment]
i use currently version 6 of angular and i recently use angular-flash-messages package. i installed it and add in my app Module but when i use it in component.ts  as a  FlashMessagesService.

` import { FlashMessagesService } from 'angular2-flash-message';  `        

but  there is error  occur  to accept FlashMessagesServices.      what can i do ?

**Comment by aZolo77** [comment]
Same question

**Comment by moff** [comment]
@jonathan-bird , @Kens1520 , @aZolo77 Sorry for the delay, folks! I've just published version 3.0.0 with Angular 6 dependency.

**Comment by aZolo77** [comment]
thats awesome and I uploadded the package, but still seeing this error:
<error TS2339: Property 'show' does not exist on type 'FlashMessagesModule'>

**Comment by moff** [comment]
> i use currently version 6 of angular and i recently use angular-flash-messages package. i installed it and add in my app Module but when i use it in component.ts as a FlashMessagesService.
> import { FlashMessagesService } from 'angular2-flash-message';
> but there is error occur to accept FlashMessagesServices. what can i do ?

> thats awesome and I uploadded the package, but still seeing this error:
<error TS2339: Property 'show' does not exist on type 'FlashMessagesModule'>

@Kens1520, @aZolo77 Are those different issues? If yes, then please create separate issues. I'll take a look at it as soon as I will have time. Thank you for letting me know!

**Comment by De4oult** [comment]
> thats awesome and I uploadded the package, but still seeing this error: <error TS2339: Property 'show' does not exist on type 'FlashMessagesModule'>

Cause you need to use "FlashMessagesService" instead of "FlashMessagesModule", 
the show() function is attached to the service, not to the module.

Replace string 
"import { FlashMessagesModule } from 'angular2-flash-messages';" 
to 
"import { FlashMessagesService } from 'angular2-flash-messages';"
